# Generated by Django 4.2.2 on 2023-07-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='note',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_body',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_title',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
