# Generated by Django 4.2.2 on 2023-07-20 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_event_end_date_event_schedule_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.event')),
            ],
        ),
    ]
