# Generated by Django 4.2.2 on 2023-07-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_event_schedule_schedule'),
        ('notes', '0004_class'),
    ]

    operations = [
    ]
