# Generated by Django 4.2.2 on 2023-07-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0005_merge_0003_remove_event_schedule_schedule_0004_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
            preserve_default=False,
        ),
    ]
