# Generated by Django 4.2.2 on 2023-07-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_event_calendar_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
