# Generated by Django 4.2.2 on 2023-07-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0007_remove_event_end_date_remove_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
        ),
    ]
