# Generated by Django 4.2.2 on 2023-07-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0008_alter_event_calendar_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.occurrence'),
        ),
    ]
