# Generated by Django 4.2.2 on 2023-07-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0009_alter_meeting_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='SchedEvent',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='event',
            new_name='occurrence',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
        ),
    ]
