# Generated by Django 4.2.2 on 2023-07-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0010_rename_event_schedevent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Lecture',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.DeleteModel(
            name='SchedEvent',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
