# Generated by Django 4.2.2 on 2023-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_rename_meeting_lecture_remove_schedule_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='startTimeDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
