# Generated by Django 4.2.2 on 2023-07-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('notes', '0011_rename_meeting_lecture_remove_schedule_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='calendar_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
        ),
        migrations.AddField(
            model_name='note',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.lecture'),
        ),
    ]
