# Generated by Django 4.2.2 on 2023-07-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_class_calendar_event_note_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.class'),
        ),
    ]
