# Generated by Django 4.2.2 on 2023-08-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_lecture_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.lecture')),
            ],
        ),
    ]
