# Generated by Django 4.2.2 on 2023-08-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_archivednote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='event',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='meeting_number',
            new_name='lecture_number',
        ),
    ]
