# Generated by Django 4.2.2 on 2023-08-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_note_associated_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='associated_color',
        ),
    ]
