# Generated by Django 4.2.2 on 2023-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_remove_note_associated_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='white', max_length=255),
            preserve_default=False,
        ),
    ]
