# Generated by Django 4.2.2 on 2023-08-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_tag_note_tag'),
        ('notes', '0020_todo'),
    ]

    operations = [
    ]
