# Generated by Django 4.2.2 on 2023-08-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        ("notes", "0021_merge_0016_tag_note_tag_0020_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar_event",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.event",
                    ),
                ),
            ],
            options={"ordering": ("name",),},
        ),
    ]
