# Generated by Django 4.2.2 on 2023-08-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_archivedclass'),
        ('notes', '0023_alter_note_tag'),
    ]

    operations = [
    ]
