# Generated by Django 4.2.2 on 2023-08-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_merge_0022_archivedclass_0023_alter_note_tag'),
        ('notes', '0024_todo_user'),
    ]

    operations = [
    ]
