# Generated by Django 4.2.2 on 2023-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_merge_20230814_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednote',
            name='title',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=31),
        ),
    ]
