# Generated by Django 4.2.2 on 2023-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_alter_archivednote_title_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArchivedClass',
        ),
    ]
