# Generated by Django 4.2.2 on 2023-08-14 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0028_class_user_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednote',
            name='color',
            field=models.CharField(default='#888888', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivednote',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
